version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rschir_buysell
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rschir_pr5
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: badhardsql!

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: badhardsql!
      MYSQL_DATABASE: rschir_pr5
      MYSQL_USER: user
      MYSQL_PASSWORD: badhardsql!
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 5
    volumes:
      - ./mysql-data:/var/lib/mysql  # Здесь определен Docker-том для сохранения данных MySQL